language: c
sudo: false
# Can't currently test Python 3 easily as >= 3.3 is required, which isn't in
# precise, and for travis is seemingly only obtainable with `language: python`,
# but then we can't test with GCC and clang.
matrix:
  include:
    - compiler: clang
      env: python=python2.7
    - compiler: gcc
      env: python=python2.7
# Try to check out a branch of the same name from the snowball-data repo
# sibling of this snowball repo, so that PRs requiring changes to both can be
# CI tested easily.
#
# If that fails, just clone the standard snowball-data repo with the same
# branch name, falling back to the default branch.
before_install:
  - git clone --depth=1 -b "$TRAVIS_BRANCH" https://github.com:"${TRAVIS_REPO_SLUG%%/*}"/snowball-data.git || git clone --depth=1 -b "$TRAVIS_BRANCH" https://github.com/snowballstem/snowball-data.git || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
script:
  - make && make check STEMMING_DATA=snowball-data
  - make check_python STEMMING_DATA=snowball-data
